# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97043091793d6fe80edd161723cd2597"
name = "free-shipping-with-remix"
application_url = "https://ii-went-draw-indirect.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cc-compliance.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_discounts,write_shipping"

[auth]
redirect_urls = [
  "https://ii-went-draw-indirect.trycloudflare.com/auth/callback",
  "https://ii-went-draw-indirect.trycloudflare.com/auth/shopify/callback",
  "https://ii-went-draw-indirect.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
